### PR TITLE
Clean output dir in delombok example

### PR DESCRIPTION
**Pull request by grv87**

### CODE REVIEW

**Comment by franzbecker** [comment]
Hey there, thanks for contributing!
I'm not sure if this is best practice or not. If we advance this a bit more it would be cool to specify the input and the output for the delombok task and write a clean task for it. What do you think?

**Comment by grv87** [comment]
Do you mean adding to `DelombokTask` designated properties for input directories and output directory?
That's a great idea. But Gradle currently doesn't support setting up several input directories using task annotations, see https://github.com/gradle/gradle/issues/5756 and next links from there.
So, that would not work for now.

On clean task, my opinion is that:
1. if clean task just removes output directory, and
2. if clean task should be run before each run of custom task

then there is no reason to have separate clean task. This just complicates build lifecycle.
In need we just run `clean` task to remove  the whole `build` directory.

**Comment by franzbecker** [comment]
Okay agreed, thanks for the input :)

**Comment by grv87** [comment]
There is still a need for custom task.
Exec doesn't accept lazy arguments for now, see e.g. gradle/gradle#4224.

Using combination of `Nested` and `InputDirectory` annotation I solved the problem mentioned earlier.
And created [DelombokExtended](https://github.com/FIDATA/gradle-base-plugins/blob/feature/delombok/src/main/groovy/org/fidata/gradle/tasks/DelombokExtended.groovy) task in my custom plugin which supports lazy configuration.
I'm not sure whether binding to source sets is good decision. But at least it works.

Also, I wanted to note on this:
> Task type for delomboking. Not added to the project by default, has to be instantiated and configured in the using gradle build

Classic approach is to have two plugins, one without default task (`base` plugin) and one with it, for `main` source set. See https://guides.gradle.org/designing-gradle-plugins/#capabilities-vs-conventions.

**Pull request merged**
